spring:
  #数据源配置
  datasource:
    username: root
    password: xc19961016
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/warehouse?serverTimezone=UTC
    #指定数据源
    type: com.alibaba.druid.pool.DruidDataSource
    #其他数据源配置
    initialSize: 5
    minIdle: 5
    maxActive: 20
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    #   配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
    durid:
      filters: stat,wall,log4j
    maxPoolPreparedStatementPerConnectionSize: 20
    useGlobalDataSourceStat: true
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500
  redis:
    host: 192.168.25.132
dubbo:
  application:
    name: provider
  registry:
    address: zookeeper://192.168.25.133:2181
  scan:
    base-packages: com.x3408.service.impl
